name: Publish 

on: 
  workflow_dispatch:
  push:
    branches:
      -main

jobs: 
  publish:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     
     - name: Setup .Net
       uses: actions/setup-dotnet@v4
       with:
         dotnet-versions: '6.0.x'
     
     - name: Restore dependencies
       run: dotnet restore ./LondonAPI.sln
       
     - name: Build
       run: dotnet build ./LondonAPI.sln --configuration Release --no-restore
     
     - name: Publish 
       run: dotnet publish ./LondonAPI.sln --configuration Release --no-build
